// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/home/nicolas-wirth/Dokumente/BA/Misc/Elliptical_Flow_Bias/./FlowMC.cc";

#endif
